/* eslint-disable */

/* prettier-ignore */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeIndexImport } from './routes/home/index'

// Create Virtual Routes

const CalendarIndexLazyImport = createFileRoute('/calendar/')()

// Create/Update Routes

const CalendarIndexLazyRoute = CalendarIndexLazyImport.update({
  path: '/calendar/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/calendar/index.lazy').then((d) => d.Route),
)

const HomeIndexRoute = HomeIndexImport.update({
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home/': {
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/calendar/': {
      preLoaderRoute: typeof CalendarIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  HomeIndexRoute,
  CalendarIndexLazyRoute,
])
